INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Suzuki',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Toyota',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Honda',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Daihatsu',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Nissan',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Chrysler',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Chevrolet',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Chery',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Changan',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Cadillac',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Buick',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Bentley',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'BMW',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Austin',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Audi',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Alfa Romeo',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Adam',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Golden Dragon',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Geely',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'GMC',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Ford',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Fiat',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'FAW',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Dongfeng',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Dodge',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Datsun',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Daewoo',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Daehan',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'DFSK',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Classic Cars',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'MG',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Lexus',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Land Rover',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Kaiser Jeep',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'KIA',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Jeep',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Jaguar',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'JW Forland',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'JAC',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Isuzu',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Hyundai',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Hummer',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Hino',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Porsche',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Plymouth',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Peugeot',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Morris',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Mitsubishi',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Mercedes Benz',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Mazda',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Master',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Maserati',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'MINI',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Willys',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Volvo',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Volkswagen',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Vauxhall',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'United',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Subaru',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'SsangYong',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Sokon',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Sogo',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Smart',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Saab',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Roma',GETDATE(),GETDATE(),1)
INSERT INTO AutoManufacturers(CreatedBy,AutoManufacturerName,CreatedOn,ModifiedOn,IsActive) VALUES (1,'Renault',GETDATE(),GETDATE(),1)



INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cultus',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Bolan',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Baleno',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Alto Lapin',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'APV',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Every',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Wagon R',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Alto',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Jimny Sierra',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Ignis',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Jimny',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Hustler',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'FX',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Every Wagon',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Ciaz',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cervo',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Celerio',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Carry',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cappuccino',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Potohar',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Palette Sw',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Palette',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mehran',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mega Carry Xtra',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Margalla',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'MR Wagon',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Lj80',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Liana',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Kizashi',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Khyber',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Kei',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vitara',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sx4',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Swift',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Spacia',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Solio',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sj410',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Samuari',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Ravi',1)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Corolla',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Coaster',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Celica',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Carina',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Camry',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cami',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'C-HR',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Belta',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'B B',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Aygo',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Avanza',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Avalon',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Auris',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Alphard G',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Allion',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'86',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Aqua',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Passo',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vitz',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Lite Ace',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Land Cruiser',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'IST',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'ISIS',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Hilux',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Hiace',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Harrier',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Fortuner',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Fj Cruiser',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Estima',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Esquire',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Duet',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Crown',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cresta',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cressida',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Corona',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Corolla Fielder',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Corolla Axio',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mark X',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mark II',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'MR2',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Lucida',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Porte',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Platz',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pixis Van',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pixis Space',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pixis Epoch',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pickup',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Noah',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Rav4',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Raum',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Ractis',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Probox',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Prius Alpha',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Premio',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Prado',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'IQ',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Yaris',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Wish',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Voxy',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Verossa',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vanguard',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Van',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Tundra',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Toyo Ace',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Town Ace',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Tank',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Tacoma',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Surf',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Succeed',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Starlet',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sprinter',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sienta',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sera',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sai',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Rush',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Runx',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Rumion',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Roomy',2)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Civic',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Acura',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Acty',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Accord Tourer',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Accord',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Wgn',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vezel',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'City',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cross Road',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cr X',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Concerto',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Civic Hybrid',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'CR-Z Sports Hybrid',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'CR-V',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Beat',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'BR-V',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Airwave',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Insight Exclusive',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Insight',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'HR-V',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Grace Hybrid',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Freed',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Fit Aria',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Fit',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Ferio',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Odyssey',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N One',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Box Slash',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Box Plus Custom',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Box Plus',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Box Custom',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'N Box',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Life',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Jade',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Integra',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Inspire',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Zest Spark',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Zest',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vamos Hobio',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vamos',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Thats',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Stream',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Spike',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'S660',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Partner',3)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Atrai Wagon',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Copen',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Coo',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Charmant',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cast',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Boon',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Bego',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sonica',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Rocky',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Move Latte',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Move Conte',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Move Canbus',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mira Gino',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Mira Cocoa',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Feroza',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Esse',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Wake',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Terios Kid',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Terios',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Tanto',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Storia',4)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'350Z',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'120 Y',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Juke',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Sunny',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Clipper',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Dayz',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Dayz Highway Star',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Note',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Navara',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Murrano',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Moco',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'March',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Kix',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Figaro',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cube',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cefiro',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Cedric',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Caravan',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'luebird Sylphy',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Blue Bird',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'AD Van',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Qashqai',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pulsar',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Primera',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pino',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Pickup',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Patrol',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Path Finder',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Otti',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Nv200 Vanette Wagon',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Vanette',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Tiida',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Terrano',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Skyline',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Serena',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Safari',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Roox',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'Wingroad',5)
INSERT INTO AutoModels(CreatedBy,CreatedOn,ModifiedOn,ModelName,AutoManufacturerId) VALUES(1,GETDATE(),GETDATE(),'X Trail',5)


			